#!/bin/bash
# Generate shared infra env files for application services.
# Reads credentials from infra setup services and writes standardized
# env files that apps consume via EnvironmentFile= directives.
#
# Runs once; skips if /var/lib/bootc-testboot/shared/.app-setup-done exists.
# Called by testboot-app-setup.service (After=mongodb-init, valkey, rabbitmq).
#
# Writes:
#   /var/lib/bootc-testboot/shared/env/mongodb.env
#   /var/lib/bootc-testboot/shared/env/valkey.env
#   /var/lib/bootc-testboot/shared/env/rabbitmq.env

set -euo pipefail
source /usr/libexec/testboot/log.sh

FLAG="/var/lib/bootc-testboot/shared/.app-setup-done"
ENV_DIR="/var/lib/bootc-testboot/shared/env"

if [ -f "$FLAG" ]; then
    log_info "App setup already done (flag exists: $FLAG)"
    exit 0
fi

log_info "Starting shared infra env file generation"

# ---------------------------------------------------------------------------
# Helper: write env file atomically with correct ownership
# ---------------------------------------------------------------------------
write_env() {
    local dest="$1"
    local content="$2"
    local tmp
    tmp=$(mktemp "${ENV_DIR}/.env-XXXXXX")
    printf '%s\n' "$content" > "$tmp"
    chmod 0640 "$tmp"
    chown root:apps "$tmp"
    mv -f "$tmp" "$dest"
    log_info "Wrote $dest"
}

# ---------------------------------------------------------------------------
# MongoDB
# ---------------------------------------------------------------------------
MONGODB_ENV="${ENV_DIR}/mongodb.env"
MONGODB_PW_FILE="/var/lib/mongodb/.admin-pw"

if [ -f "$MONGODB_PW_FILE" ]; then
    MONGODB_PW=$(cat "$MONGODB_PW_FILE")
    write_env "$MONGODB_ENV" "\
# Generated by testboot-app-setup.sh — do not edit
# TLS not needed: mongod binds 127.0.0.1 with preferTLS (plain connections accepted)
MONGODB_HOST=127.0.0.1
MONGODB_PORT=27017
MONGODB_USERNAME=admin
MONGODB_PASSWORD=${MONGODB_PW}
MONGODB_URI=mongodb://admin:${MONGODB_PW}@127.0.0.1:27017/?replicaSet=rs0"
    unset MONGODB_PW
else
    log_warn "MongoDB password file not found ($MONGODB_PW_FILE) — skipping mongodb.env"
fi

# ---------------------------------------------------------------------------
# Valkey (no auth by default — host/port only)
# ---------------------------------------------------------------------------
VALKEY_ENV="${ENV_DIR}/valkey.env"

write_env "$VALKEY_ENV" "\
# Generated by testboot-app-setup.sh — do not edit
VALKEY_HOST=127.0.0.1
VALKEY_PORT=6379
REDIS_URL=redis://127.0.0.1:6379"

# ---------------------------------------------------------------------------
# RabbitMQ
# ---------------------------------------------------------------------------
RABBITMQ_ENV="${ENV_DIR}/rabbitmq.env"
RABBITMQ_PW_FILE="/var/lib/rabbitmq/.admin-pw"

if [ -f "$RABBITMQ_PW_FILE" ]; then
    RABBITMQ_PW=$(cat "$RABBITMQ_PW_FILE")
    write_env "$RABBITMQ_ENV" "\
# Generated by testboot-app-setup.sh — do not edit
RABBITMQ_HOST=127.0.0.1
RABBITMQ_PORT=5672
RABBITMQ_MANAGEMENT_PORT=15672
RABBITMQ_USERNAME=admin
RABBITMQ_PASSWORD=${RABBITMQ_PW}
AMQP_URL=amqp://admin:${RABBITMQ_PW}@127.0.0.1:5672/"
    unset RABBITMQ_PW
else
    # Fallback: default guest credentials (matches rabbitmq.conf)
    log_warn "RabbitMQ password file not found ($RABBITMQ_PW_FILE) — using defaults"
    write_env "$RABBITMQ_ENV" "\
# Generated by testboot-app-setup.sh — do not edit (default credentials)
RABBITMQ_HOST=127.0.0.1
RABBITMQ_PORT=5672
RABBITMQ_MANAGEMENT_PORT=15672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest
AMQP_URL=amqp://guest:guest@127.0.0.1:5672/"
fi

touch "$FLAG"
chmod 0640 "$FLAG"
chown root:apps "$FLAG"
log_info "Shared infra env files generated successfully"
