#!/bin/bash
# Initialize MongoDB replica set and create admin user.
# Runs once after first boot; skips if already initialized.
#
# Requires:
#   - mongod running with auth enabled
#   - /var/lib/mongodb/.admin-pw (generated by mongodb-setup.service)
#
# Uses MongoDB's localhost exception to create the first user.
# The localhost exception ONLY allows createUser on the admin database;
# it does NOT allow getUser, listUsers, or other read commands.
# Therefore: call createUser directly and catch "already exists".
#
# Connection: mongosh to mongodb://127.0.0.1:27017/ without TLS. With
# net.tls.mode preferTLS (see mongod.conf), plain localhost is allowed;
# do not use --tls here without --tlsCAFile (handshake can fail).

set -euo pipefail
source /usr/libexec/testboot/log.sh

FLAG="/var/lib/mongodb/.rs-initialized"
if [ -f "$FLAG" ]; then
    log_info "MongoDB already initialized (flag exists: $FLAG)"
    exit 0
fi

log_info "Starting MongoDB initialization (rs0 + admin user)"

ADMIN_PW_FILE="/var/lib/mongodb/.admin-pw"
if [ ! -f "$ADMIN_PW_FILE" ]; then
    log_error "Admin password file not found: $ADMIN_PW_FILE"
    exit 1
fi
ADMIN_PW=$(cat "$ADMIN_PW_FILE")

export MONGOSH_ADMIN_PW="$ADMIN_PW"
trap 'unset MONGOSH_ADMIN_PW 2>/dev/null || true' EXIT

# --- Step 1: Initiate replica set (if not already done) ---
log_info "Step 1/2: Checking replica set status"
mongosh --quiet "mongodb://127.0.0.1:27017/" --eval '
  let initialized = false;
  try { initialized = (rs.status().ok === 1); } catch(e) {}

  if (!initialized) {
    print("INIT: rs.initiate() starting");
    rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "localhost:27017" }] });
    let ready = false;
    for (let i = 0; i < 30; i++) {
      if (db.hello().isWritablePrimary) { ready = true; break; }
      sleep(2000);
    }
    if (!ready) { throw new Error("rs0 primary election timed out after 60s"); }
    print("INIT: rs0 primary elected");
  } else {
    print("INIT: rs0 already initialized, skipping");
  }
'
log_info "Step 1/2: Replica set rs0 is ready"

# --- Step 2: Create admin user via localhost exception ---
# The localhost exception ONLY allows createUser (not getUser).
# If the user already exists, MongoDB returns error code 51003.
log_info "Step 2/2: Creating admin user via localhost exception"
mongosh --quiet "mongodb://127.0.0.1:27017/" --eval '
  const adminDb = db.getSiblingDB("admin");
  const pw = process.env.MONGOSH_ADMIN_PW;
  if (!pw) { throw new Error("MONGOSH_ADMIN_PW not set"); }

  try {
    adminDb.createUser({
      user: "admin",
      pwd: pw,
      roles: ["root"]
    });
    print("INIT: admin user created");
  } catch(e) {
    // 51003 = "User \"admin@admin\" already exists"
    if (e.code === 51003) {
      print("INIT: admin user already exists, skipping");
    } else {
      throw e;
    }
  }
'

touch "$FLAG"
log_info "MongoDB initialization complete: rs0 + admin user"
