#!/bin/bash
# Initialize MongoDB replica set and create admin user.
# Runs once after first boot; skips if already initialized.
#
# Requires:
#   - mongod running with auth enabled
#   - /var/lib/mongodb/.admin-pw (generated by mongodb-setup.service)
#
# Uses MongoDB's localhost exception to create the first user
# before auth takes effect.

set -euo pipefail
source /usr/libexec/testboot/log.sh

FLAG="/var/lib/mongodb/.rs-initialized"
if [ -f "$FLAG" ]; then
    log_info "MongoDB already initialized"
    exit 0
fi

ADMIN_PW=$(cat /var/lib/mongodb/.admin-pw)

mongosh --quiet --tls --tlsAllowInvalidCertificates --eval "
  if (rs.status().ok !== 1) {
    rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] });
    while (!rs.isMaster().ismaster) { sleep(1000); }
  }
  const adminDb = db.getSiblingDB('admin');
  if (adminDb.getUser('admin') === null) {
    adminDb.createUser({
      user: 'admin',
      pwd: '${ADMIN_PW}',
      roles: ['root']
    });
  }
"

touch "$FLAG"
log_info "MongoDB initialized: rs0 + admin user created"
