#!/bin/bash
# Initialize MongoDB replica set and create admin user.
# Runs once after first boot; skips if already initialized.
#
# Requires:
#   - mongod running with auth enabled
#   - /var/lib/mongodb/.admin-pw (generated by mongodb-setup.service)
#
# Uses MongoDB's localhost exception to create the first user
# before auth takes effect.

set -euo pipefail
source /usr/libexec/testboot/log.sh

FLAG="/var/lib/mongodb/.rs-initialized"
if [ -f "$FLAG" ]; then
    log_info "MongoDB already initialized"
    exit 0
fi

ADMIN_PW=$(cat /var/lib/mongodb/.admin-pw)

mongosh --quiet --tls --tlsAllowInvalidCertificates --eval "
  let initialized = false;
  try { initialized = (rs.status().ok === 1); } catch(e) {}

  if (!initialized) {
    rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] });
    let ready = false;
    for (let i = 0; i < 30; i++) {
      if (db.hello().isWritablePrimary) { ready = true; break; }
      sleep(2000);
    }
    if (!ready) { throw new Error('rs0 primary election timed out after 60s'); }
  }

  const adminDb = db.getSiblingDB('admin');
  if (adminDb.getUser('admin') === null) {
    adminDb.createUser({
      user: 'admin',
      pwd: '${ADMIN_PW}',
      roles: ['root']
    });
  }
"

touch "$FLAG"
log_info "MongoDB initialized: rs0 + admin user created"
