name: Free disk space
description: Reclaim disk space on GitHub-hosted runners by removing unused toolchains

runs:
  using: composite
  steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
